//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyDiaryApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DailyDiaryApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT name from master.dbo.sysdatabases WHERE name=N&apos;DailyDiary&apos;)
        ///	DROP DATABASE DailyDiary
        ///
        ///CREATE DATABASE DailyDiary
        ///GO
        ///
        ///USE DailyDiary
        ///GO
        ///
        ///CREATE TABLE [dbo].[User](
        ///	[Id] [int] IDENTITY(1,1) PRIMARY KEY CLUSTERED,
        ///	[Name] [nvarchar](50) NOT NULL UNIQUE
        ///)
        ///
        ///GO
        ///
        ///CREATE TABLE [dbo].[Entry](
        ///	[Id] [int] IDENTITY(1,1) PRIMARY KEY CLUSTERED,
        ///	[UserId] [int] NOT NULL REFERENCES [dbo].[User](Name),
        ///	[Time] [datetimeoffset](7) NOT NULL,
        ///	[Title] [nvarchar](50) NOT NULL,
        ///	[Content [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DbSchema {
            get {
                return ResourceManager.GetString("DbSchema", resourceCulture);
            }
        }
    }
}
